title: ESCOBAR, blog!
author: Escobar
email: info@escobar.eu.org
url: https://daeshu.github.io/ns # root address of the site
baseurl: "/ns" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: >
  Algunos apuntes.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "Atr√°s" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
